title: My Learning Journey Of Design Analysis And Algorithm.
description: This Site is my learning outcomes and exibition of projects throughout the course and the insightful perspectives gained.
theme: jekyll-theme-modernist
